- hosts: all
  tasks:
  - name: Install Prerequisites
    import_role:
      name: ansible-role-prerequisites

  - name: Install OpenJDK
    import_role:
      name: ansible-role-openjdk

  - name: Clone Repo
    git:
      repo: https://github.com/ikambarov/spring-petclinic.git
      dest: /spring

  - name: Run Maven Wrapper
    shell: "./mvnw package"
    args:
      chdir: /spring
      creates: /spring/target

  - name: Start App
    shell: ' nohup java -jar target/*.jar &'
    args:
      chdir: /spring


